swagger: "2.0"
info:
  version: 1.0.0
  description: "This is the cinema API"
  title: "Cinema API "
  contact:
    email: "morgan.liang@unsw.edu.au"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "cinema.swagger.io"
basePath: "/v1"
tags:
- name: "Cinema"
  description: "Cinema Service"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"


schemes:
- "http"
paths:
  /Cinema:
    get:
      tags:
      - "default"
      operationId: "get_all_cinemas"
      summary: "return all cinemas"
      description: "Get all available cinemas"
      
      produces:
      - "application/json"
      
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items: 
              $ref: '#/definitions/cinema'
        404:
          description: "Not Found"
        
        500:
          description: "Internal server error"
        
        
          
  /Cinema/{cinema_name}:
    get:
      operationId: "get_cinema"
      parameters:
        - name: "cinema_name"
          in: "path"
          type: "string"
          default: "cinema1"
          required: true
      summary: "gets information on cinema id"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/cinema'
              
        404:
          description: "Not Found"
        
        500:
          description: "Internal server error"
          
        
  
  
definitions:
  cinema:
    type: object
    properties:
      c_id:
        type: integer
        example: 1
      name:
        type: string
        example: "cinema1"
      address:
        type: string
        example: "Broadway"
      phone:
        type: string
        example: "0296969696"
      snacks:
        type: array
        items: 
          type: string
        example: ["hotdog", "chips", "chocolate"]
      #now showing
      movies:
        type: array
        items:
          $ref: '#/definitions/movie'
        
        
    required:
      - c_id
      - name
    
    
  movie:
    type: object
    properties:
      m_id:
        type: integer
        example: 1
      cinema_name:
        type: string
        example: "Broadway"
      name:
        type: string
        example: "The Matrix"
      description:
        type: string
        example: "Sick future movie"
    required:
      - m_id
      - name
      - description
  
  
  # Day 1-Monday, 2-Tuesday, 3-Wed, 4-Thur, 5-Fri, 6-Sat, NO SUN
  timeslot:
    type: object
    properties:
      t_id:
        type: integer
        example: 1
      cinema_name:
        type: string
        example: "Broadway"
      movie_name:
        type: string
        example: "The Matrix"
      theatre_type:
        type: string
        enum:
          - "Lux"
          - "Saver"
          - "VMax"
      d_time:
        type: string
        format: date-time
        example: "2017-07-21T17:32:28Z"
        description: date-time=(fullyear)-(month)-(mday)T(hour):(minute):(time)-(second)
      max_seats:
        type: integer
        example: 100
      avail_seats:
        type: integer
        example: 50
      
  
    

             
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
  
  
  
  
  
  
  
  
  
  